# Generated by Django 6.0.5 on 2026-06-05 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_paciente_medica_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('tipo', models.CharField(max_length=80, verbose_name='Tipo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('intensidade', models.PositiveSmallIntegerField(blank=True, help_text='Opcional, de 1 (leve) a 5 (intensa).', null=True, verbose_name='Intensidade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_sintomas', to='usuarios.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Registro de sintoma',
                'verbose_name_plural': 'Registros de sintomas',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
