# Generated by Django 6.0.5 on 2026-06-04 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Etapa do tratamento',
                'verbose_name_plural': 'Etapas do tratamento',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição simples')),
                ('indicacao', models.TextField(blank=True, verbose_name='Indicação geral')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tratamento',
                'verbose_name_plural': 'Tratamentos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='OrientacaoTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('categoria', models.CharField(blank=True, max_length=80, verbose_name='Categoria')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orientacoes', to='tratamentos.etapatratamento', verbose_name='Etapa relacionada')),
                ('tratamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orientacoes', to='tratamentos.tratamento', verbose_name='Tratamento relacionado')),
            ],
            options={
                'verbose_name': 'Orientação do tratamento',
                'verbose_name_plural': 'Orientações do tratamento',
                'ordering': ['categoria', 'titulo'],
            },
        ),
        migrations.AddField(
            model_name='etapatratamento',
            name='tratamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='tratamentos.tratamento', verbose_name='Tratamento'),
        ),
    ]
