# Generated by Django 6.0.5 on 2026-06-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicionario', '0002_termodicionario_artigos_relacionados'),
        ('tratamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orientacaotratamento',
            name='termos_relacionados',
            field=models.ManyToManyField(blank=True, related_name='orientacoes', to='dicionario.termodicionario', verbose_name='Termos do dicionário relacionados'),
        ),
        migrations.AddField(
            model_name='tratamento',
            name='termos_relacionados',
            field=models.ManyToManyField(blank=True, related_name='tratamentos', to='dicionario.termodicionario', verbose_name='Termos do dicionário relacionados'),
        ),
    ]
