# Generated by Django 6.0.5 on 2026-06-05 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamentos', '0002_orientacaotratamento_termos_relacionados_and_more'),
        ('usuarios', '0002_paciente_medica_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaJornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('concluida', 'Concluída'), ('atual', 'Atual'), ('futura', 'Futura')], default='futura', max_length=20, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='tratamentos.etapatratamento', verbose_name='Etapa do tratamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornada', to='usuarios.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Etapa da jornada',
                'verbose_name_plural': 'Etapas da jornada',
                'ordering': ['etapa__ordem', 'etapa__id'],
                'unique_together': {('paciente', 'etapa')},
            },
        ),
    ]
