# Generated by Django 6.0.5 on 2026-06-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamentos', '0003_etapajornada'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapatratamento',
            name='duracao_estimada_dias',
            field=models.PositiveIntegerField(blank=True, help_text='Estimativa, definida pela clínica, de quantos dias esta etapa costuma levar até a próxima. Usada como previsão na linha do tempo; é só uma estimativa, nunca um prazo garantido.', null=True, verbose_name='Duração estimada (dias)'),
        ),
    ]
