# Generated by Django 6.0.5 on 2026-06-17 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoPrivacidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('correcao', 'Correcao de dados'), ('exclusao', 'Exclusao / anonimizacao')], max_length=20, verbose_name='Tipo')),
                ('mensagem', models.TextField(help_text='O que deve ser corrigido, ou o motivo do pedido de exclusao.', verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluida'), ('recusada', 'Recusada')], default='pendente', max_length=20, verbose_name='Status')),
                ('resposta', models.TextField(blank=True, verbose_name='Resposta da clinica')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_privacidade', to=settings.AUTH_USER_MODEL, verbose_name='Titular')),
            ],
            options={
                'verbose_name': 'Solicitacao de privacidade',
                'verbose_name_plural': 'Solicitacoes de privacidade',
                'ordering': ['-criada_em', '-id'],
            },
        ),
    ]
