# Generated by Django 6.0.5 on 2026-06-07 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_paciente_medica_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCiclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('etapa', models.CharField(choices=[('menstruacao', 'Menstruação'), ('folicular', 'Fase folicular'), ('ovulacao', 'Ovulação'), ('lutea', 'Fase lútea')], default='menstruacao', help_text='Use "Menstruação" para marcar o primeiro dia do período.', max_length=20, verbose_name='Etapa do ciclo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('registrado', 'Registrado'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído')], default='registrado', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ciclo', to='usuarios.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Registro de ciclo',
                'verbose_name_plural': 'Registros de ciclo',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
