# Generated by Django 6.0.3 on 2026-06-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciclo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrociclo',
            name='status',
        ),
    ]
