# Generated by Django 6.0.3 on 2026-06-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciclo', '0002_remove_registrociclo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrociclo',
            name='etapa_ciclo',
            field=models.CharField(choices=[('Menstruação', 'Menstruação'), ('Fase Folicular', 'Fase Folicular'), ('Ovulação', 'Ovulação'), ('Fase Lútea', 'Fase Lútea')], max_length=20, verbose_name='Etapa do ciclo'),
        ),
    ]
