# Generated by Django 6.0.5 on 2026-06-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='Título')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('categoria', models.CharField(blank=True, max_length=80, verbose_name='Categoria')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Conteúdo de apoio',
                'verbose_name_plural': 'Conteúdos de apoio',
                'ordering': ['ordem', 'titulo'],
            },
        ),
    ]
