# Generated by Django 6.0.5 on 2026-06-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
        ('usuarios', '0002_paciente_medica_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidade',
            name='medicas',
            field=models.ManyToManyField(blank=True, related_name='especialidades', to='usuarios.medica', verbose_name='Médicas relacionadas'),
        ),
    ]
