# Generated by Django 6.0.5 on 2026-06-05 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_especialidade_medicas'),
        ('usuarios', '0002_paciente_medica_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_horario', models.DateTimeField(verbose_name='Data e horário')),
                ('tipo', models.CharField(choices=[('exame', 'Exame'), ('procedimento', 'Procedimento'), ('medicacao', 'Medicação'), ('lembrete', 'Lembrete'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Tipo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='usuarios.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Evento do tratamento',
                'verbose_name_plural': 'Eventos do tratamento',
                'ordering': ['data_horario'],
            },
        ),
    ]
