# Generated by Django 6.0.5 on 2026-05-26 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('dose', models.CharField(blank=True, max_length=80, verbose_name='Dose')),
                ('horario', models.TimeField(blank=True, null=True, verbose_name='Horário')),
                ('instrucoes', models.TextField(blank=True, verbose_name='Instruções')),
                ('tomado_hoje', models.BooleanField(default=False, verbose_name='Tomado hoje')),
                ('data_ultima_marcacao', models.DateField(blank=True, null=True, verbose_name='Data da última marcação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='usuarios.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['horario', 'nome'],
            },
        ),
    ]
