# Generated by Django 6.0.5 on 2026-06-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='armazenamento',
            field=models.CharField(blank=True, max_length=200, verbose_name='Armazenamento'),
        ),
    ]
