# Generated by Django 6.0.5 on 2026-06-12 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaAssistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intencao', models.CharField(max_length=60, unique=True, verbose_name='Intenção')),
                ('pergunta_exemplo', models.CharField(max_length=160, verbose_name='Pergunta de exemplo')),
                ('palavras_chave', models.TextField(help_text='Separadas por vírgula ou espaço; usadas para casar a pergunta (sem distinção de acento ou maiúsculas).', verbose_name='Palavras-chave')),
                ('resposta', models.TextField(verbose_name='Resposta')),
                ('categoria', models.CharField(blank=True, max_length=60, verbose_name='Categoria')),
                ('fonte_rotulo', models.CharField(blank=True, max_length=120, verbose_name='Rótulo da fonte')),
                ('fonte_rota', models.CharField(blank=True, max_length=120, verbose_name='Rota da fonte')),
                ('sensivel', models.BooleanField(default=False, help_text='Se marcada, a resposta reforça o encaminhamento à clínica.', verbose_name='Tema sensível')),
                ('prioridade', models.PositiveIntegerField(default=0, help_text='Desempata quando mais de uma casa.', verbose_name='Prioridade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
            ],
            options={
                'verbose_name': 'Resposta do assistente',
                'verbose_name_plural': 'Respostas do assistente',
                'ordering': ['-prioridade', 'categoria', 'pergunta_exemplo'],
            },
        ),
        migrations.CreateModel(
            name='AcaoAssistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(max_length=80, verbose_name='Rótulo')),
                ('rota', models.CharField(max_length=120, verbose_name='Rota no app')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='assistente.respostaassistente', verbose_name='Resposta')),
            ],
            options={
                'verbose_name': 'Ação do assistente',
                'verbose_name_plural': 'Ações do assistente',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
