# Generated by Django 6.0.5 on 2026-05-25 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('paciente', 'Paciente'), ('medica', 'Médica'), ('admin', 'Administradora')], default='paciente', max_length=20, verbose_name='Tipo de usuário')),
                ('nome_completo', models.CharField(blank=True, max_length=180, verbose_name='Nome completo')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('foto_url', models.URLField(blank=True, verbose_name='Foto (URL)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de usuário',
                'verbose_name_plural': 'Perfis de usuários',
                'ordering': ['nome_completo', 'usuario__username'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('tipo_sanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('desconhecido', 'Desconhecido')], default='desconhecido', max_length=15, verbose_name='Tipo sanguíneo')),
                ('medicamentos_em_uso', models.TextField(blank=True, verbose_name='Medicamentos em uso')),
                ('observacoes_medicas', models.TextField(blank=True, verbose_name='Observações médicas')),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='usuarios.perfilusuario', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Medica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm', models.CharField(blank=True, max_length=30, verbose_name='CRM')),
                ('especialidade', models.CharField(blank=True, max_length=120, verbose_name='Especialidade')),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medica', to='usuarios.perfilusuario', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Médica',
                'verbose_name_plural': 'Médicas',
            },
        ),
    ]
