# Generated by Django 6.0.5 on 2026-06-11 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_paciente_medica_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipeCuidadoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('responsavel', 'Responsável'), ('colaboradora', 'Colaboradora'), ('substituta', 'Substituta')], default='colaboradora', max_length=20, verbose_name='Papel no cuidado')),
                ('ativa', models.BooleanField(default=True, verbose_name='Vínculo ativo')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_cuidado', to='usuarios.medica', verbose_name='Médica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe_cuidado', to='usuarios.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Vínculo de equipe de cuidado',
                'verbose_name_plural': 'Equipe de cuidado das pacientes',
                'ordering': ['-criada_em', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativa', True)), fields=('paciente', 'medica'), name='vinculo_cuidado_ativo_unico')],
            },
        ),
    ]
