# Generated by Django 6.0.5 on 2026-06-17 02:27

import django.db.models.deletion
import usuarios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_conviteacesso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecuperacaoSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=usuarios.models.gerar_token_recuperacao, editable=False, max_length=128, unique=True, verbose_name='Token')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('usado', 'Usado')], default='pendente', max_length=20, verbose_name='Status')),
                ('expira_em', models.DateTimeField(default=usuarios.models.prazo_padrao_recuperacao, verbose_name='Expira em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('usado_em', models.DateTimeField(blank=True, null=True, verbose_name='Usado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuperacoes_senha', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Recuperação de senha',
                'verbose_name_plural': 'Recuperações de senha',
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
