# Generated by Django 6.0.5 on 2026-06-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_recuperacaosenha'),
    ]

    operations = [
        migrations.AddField(
            model_name='medica',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Apresentação'),
        ),
        migrations.AddField(
            model_name='medica',
            name='rqe',
            field=models.CharField(blank=True, max_length=30, verbose_name='RQE'),
        ),
    ]
