# Generated by Django 6.0.5 on 2026-05-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermoDicionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=120, unique=True, verbose_name='Termo')),
                ('definicao', models.TextField(verbose_name='Definição')),
                ('categoria', models.CharField(blank=True, max_length=80, verbose_name='Categoria')),
                ('exemplo', models.TextField(blank=True, verbose_name='Exemplo de uso')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Termo do dicionário',
                'verbose_name_plural': 'Termos do dicionário',
                'ordering': ['termo'],
            },
        ),
    ]
