# Generated by Django 6.0.5 on 2026-05-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termodicionario',
            name='artigos_relacionados',
            field=models.JSONField(blank=True, default=list, help_text='Lista de objetos {"titulo": "...", "url": "..."} apontando para artigos sobre o termo. Pode ficar vazia.', verbose_name='Artigos relacionados'),
        ),
    ]
