# Generated by Django 6.0.5 on 2026-06-11 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_equipecuidadopaciente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('assumir_atendimento', 'Assumiu o atendimento'), ('visualizar_paciente', 'Visualizou a paciente'), ('editar_paciente', 'Editou a paciente'), ('criar_consulta', 'Criou uma consulta'), ('criar_medicamento', 'Cadastrou um medicamento')], max_length=40, verbose_name='Ação')),
                ('entidade', models.CharField(blank=True, choices=[('paciente', 'Paciente'), ('consulta', 'Consulta'), ('medicamento', 'Medicamento'), ('equipe_cuidado', 'Equipe de cuidado')], max_length=30, verbose_name='Entidade')),
                ('entidade_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID da entidade')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_atividade', to='usuarios.paciente', verbose_name='Paciente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_atividade', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de atividade',
                'verbose_name_plural': 'Logs de atividade',
                'ordering': ['-data_hora', '-id'],
            },
        ),
    ]
